version: "3"

services:
  db:
    image: postgres:16
    volumes:
      - MessangerBackDb:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - MessangerBack-network
    container_name: db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_storage:/data
    networks:
      - MessangerBack-network
    container_name: redis

  # backapi:
  #   image: ${DOCKER_REGISTRY-}backapi
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=5000
  #   networks:
  #     - MessangerBack-network
  #   container_name: api
  #   depends_on:
  #     - db
  #     - redis

networks:
  MessangerBack-network:

volumes:
  MessangerBackDb:
  redis_storage:
